### ISSUE TITLE
AHCC link broken

### ISSUE THREAD

**Issue by paulwratt** [freemint/teradesk#1]
just tried to download AHCC via the link in the readme (thruogh github) and it appears his sit has gone.

also is this repo ahead or behind the 4.08 one here (it does not say its behind - like it used to?):
https://github.com/mikrosk/teradesk

Is Henk ok?

**Comment by th-otto** [comment]
On Mittwoch, 28. April 2021 06:00:04 CEST Paul Wratt wrote:
> Is Henk ok?

He announced awhile back that 6.0 was his last release, but i have no idea why 
his site(s) are down.

**Comment by paulwratt** [comment]
is it worth posting a v6 AHCC zip archive in TeraDesk somewhere. If not can you email me a copy via the list? Or is ther another public copy somewhere?

**Comment by mikrosk** [comment]
https://storage.atari-source.org/atari/mirrors/kurobox.serveftp.net/programming/ahcc/

**Comment by paulwratt** [comment]
thank, I was just about to post a link - probably a good idea to leave this issue open
