### ISSUE TITLE
Current TeraDesk is about 100K larger than the last 4.08 release

### ISSUE THREAD

**Issue by mikrosk** [freemint/teradesk#2]
Just noticed this. It is without doubt caused by linking against mintlib because as I see we still support PureC project files where build sizes are as they used to be (however for m68k builds only).

@th-otto I'm wondering how much pain would be to use libcmini for this project so we could have just one toolchain to use?

**Comment by th-otto** [comment]
Probably not more than in other projects where we switched to libcmini. However i would still prefer to build the 68k version with Pure-C.

**Comment by th-otto** [comment]
Could we close this? The current build system works, and i prefer to leave it as is, rather than to have to put effort into using libcmini just for a better feeling to use just one toolchain.

**Comment by mikrosk** [comment]
Sure, #3 is a far more painful issue on my wishlist to fix. :)
