### ISSUE TITLE
TeraDesk Load configuration

### ISSUE THREAD

**Issue by latzmaster** [freemint/teradesk#5]
Perhaps related to #4
I found an issue with TeraDesk and "Load configuration", please try:
- Remove some icons (files, folders) from your current desktop.
- Do "Save config as..." and save teradesk.inf somewhere.
- Do "Load config...", reload your previous config from teradesk folder

Now, results are different, perhaps depending to the number of removed
icons and/or assignments:

- PRG and/or file assignments don't work anymore.
- In TeraDesk menu "View", the shortcut "^R" which i set for "Auto
  arrange" is also written at the first 2 positions of separator line
  underneath.

This happens with extended and original CICONS.RSC, english and german
resource, on Falcon and FireBee.
Any .inf loaded at TeraDesk start works correct, happens only with menu
function.

Can anybody confirm this?

And a feature request: It would be great if TeraDesk could load/save its .inf
prefering from $HOME (if present).

**Comment by th-otto** [comment]
#4 should be fixed now. Can you retry with the new version?

**Comment by latzmaster** [comment]
Could you provide a compiled package for testing, please?
Or did i miss it somewhere?

**Comment by th-otto** [comment]
Oops, thought it was mentioned in the readme, but snapshots are available here:
https://tho-otto.de/snapshots/teradesk/teradesk-latest.zip

**Comment by latzmaster** [comment]
This is fixed, great!! (Also #4)
Thank you!!
